import { chromium } from 'playwright';
const pick = process.argv[2] || 'cat';
const OUT = '/home/user/mofumofu/docs/verification/intro/' + (process.env.TAG || '');
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=swiftshader','--enable-unsafe-swiftshader','--autoplay-policy=no-user-gesture-required'] });
const ctx = await b.newContext({ viewport: { width: +(process.env.W || 390), height: +(process.env.H || 844) }, deviceScaleFactor: 2, hasTouch: true, isMobile: true });
const page = await ctx.newPage();
const errs = [];
page.on('pageerror', e => errs.push('pageerror ' + e.message + ' | ' + String(e.stack).split('\n').slice(0,4).join(' ; ')));
page.on('console', m => { if (m.type() === 'error') errs.push('console ' + m.text()); });
await page.goto(process.env.URL || 'http://127.0.0.1:5199/');
await page.waitForSelector('#g-start');
const shot = (n) => page.screenshot({ path: OUT + `${pick}-${n}.png` });
await shot('00-gate');
const t0 = Date.now();
await page.tap('#g-start');
const at = async (sec, name) => { const d = sec * 1000 - (Date.now() - t0); if (d > 0) await page.waitForTimeout(d); await shot(name); console.log(name, ((Date.now() - t0) / 1000).toFixed(1), JSON.stringify(await page.evaluate(() => document.querySelector('#intro-sys')?.innerText))); };
await at(6, '01-boot');
await at(17, '02-record');
await at(22, '03-caption1');
await at(28, '04-caption2');
await at(33, '05-lost');
await at(37, '06-restore1');
await at(41, '07-restore2');
await at(47, '08-restore3');
await at(52, '09-room');
await page.waitForSelector('.intro.show-pets');
await page.waitForTimeout(3000);
await shot('10-select');
const other = pick === 'cat' ? 'dog' : 'cat';
await page.tap(`#i-${other}`);
await page.waitForTimeout(1200); await shot('11-other-reaction');
await page.waitForTimeout(3600); await shot('12-other-confirm');
await page.tap('#c-no');
await page.waitForTimeout(2200); await shot('13-back');
await page.tap(`#i-${pick}`);
await page.waitForTimeout(1500); await shot('14-pick-reaction');
await page.waitForTimeout(3200); await shot('15-confirm');
await page.tap('#c-yes');
await page.waitForTimeout(3500); await shot('16-registered');
await page.waitForSelector('#pet-name-in', { state: 'visible' });
await page.waitForTimeout(800); await shot('17-name');
await page.fill('#pet-name-in', 'ミケ');
await page.waitForTimeout(300); await shot('18-name-filled');
await page.tap('.intro-name button');
await page.waitForTimeout(1600); await shot('19-registered-name');
await page.waitForTimeout(3600); await shot('20-day01');
await page.waitForSelector('.intro', { state: 'detached', timeout: 15000 }).catch(async e => { console.log('NOT DETACHED', errs, await page.evaluate(() => document.querySelector('.intro')?.className)); });
await page.waitForTimeout(2000); await shot('21-home');
console.log('feedback:', await page.innerText('.log .now'));
await page.tap('[data-action=feed]');
await page.waitForTimeout(600); await shot('22-feed-dialog');
await page.tap('#foods button >> nth=0').catch(()=>{});
await page.waitForTimeout(500);
console.log('after feed click fb:', await page.innerText('.log .now'));
await page.waitForTimeout(1200); await shot('23-fed');
await page.waitForTimeout(3500); await shot('24-looks');
const box = await page.locator('#dog').boundingBox();
await page.touchscreen.tap(box.x + box.width/2, box.y + box.height/2);
await page.waitForTimeout(900); await shot('25-petted');
await page.waitForTimeout(1500); console.log('fb1', await page.innerText('.log .now'));
await page.waitForTimeout(2000); console.log('fb2', await page.innerText('.log .now')); await shot('26-sys-line');
await page.waitForTimeout(4500); console.log('fb3', await page.innerText('.log .now')); await shot('27-water-hint');
console.log('save', await page.evaluate(() => { const s = JSON.parse(localStorage.getItem('mofumofu-save-v3')); return [s.game.species, s.tutorial, s.game.name, s.game.food, s.game.pet.full]; }));
console.log('errors', errs);
await b.close();
